---
dist: bionic
language: python
python:
    - '3.6'
sudo: true
addons:
    apt:
      sources:
        - sourceline: ppa:nextgis/ppa
      packages:
          - gdal-bin
          - gdal-data
          - libgdal-dev
          - libgdal20
          - libudunits2-0
          - gfortran
          - libatlas-base-dev
          - liblapack-dev
          - libproj-dev
          - libxml2-dev
          - libxslt-dev
          - pandoc
          - shellcheck


git:
  # We need a deeper depth for 'git descibe' to ensure
  # we can reach the last tagged version.
  depth: 99999

install:
    - export CPLUS_INCLUDE_PATH="/usr/include/gdal"
    - export C_INCLUDE_PATH="/usr/include/gdal"
    - export GDAL_DATA="$(gdal-config --datadir)"
    - travis_retry pip install pylint==1.7.4 yamllint pytest-cov pycodestyle coveralls netCDF4==1.3.1
    - gdal-config --version
    - pip install GDAL=="$(gdal-config --version)"
    - travis_retry pip install --extra-index-url=https://packages.dea.ga.gov.au/ eodatasets digitalearthau
    - pip install -e .
    # For debugging
    - pip freeze

script:
    - ./check-code.sh

after_success:
    - coveralls

before_deploy:
    - pip wheel --no-deps -w dist .

deploy:
 - provider: s3
   bucket: "datacube-core-deployment"
   region: "ap-southeast-2"
   local_dir: dist
   upload_dir: fc
   skip_cleanup: true
   on:
       all_branches: true  # Let the condition below decide if the branch is to be deployed
       condition: $TRAVIS_BRANCH = "master" || ! -z "${TRAVIS_TAG}"  # master branch or tags
       repo: GeoscienceAustralia/fc
       python: "3.6"

notifications:
    slack:
        on_success: change
        on_failure: always
        rooms:
            secure: kju0+7y8Qoo6Wn2QdaVo67fKizx1OvcZVgGulx88UXBPe89zm6bRrbW9lATJnl0Epa4WdoCSAqgfyEM3oGrJDH/cIDx4EnmRgZ+Yt4aPF7orllFCxw+yOFbH/axVr1fOr/7fxilkUwAXgwFNz/maEbRDj6wSH6xkaYEVMw5Waou36dZvwZYVBByS4eFaMLSk5IxpcHzgH+8bVmZO14dzBTGKbm17b2eC8bzedp9MyQNy3HR4odSDTp8m0XYuH3elACUBZusmfDlCAmyG5b2CNTByS2L6l99oaXAWYWjU6JmucVBHJQd3qwTbHGmHMCPgyVWyGFqZgt50kePQis6HTeVDPrCCfHgBp+6TFki1kmsW6V0WMIHA1oQAbZdEayjDzDBXYWTvP64D4GxdH8EKRkHrlANQJmeS4+z3GWY/Thr1QqFFzFKyASuujPiXTVVXV+GasaYRULlB+QikAXPIwvshVuI3fipnz2zdUDeWRqFXyldhxvo7/IwcRdDwSVf5uquOWGB/mOkZtYYkO0tadLPOTEQNKAkmPPGLDcirUhetIZpiILNuuW4E5EyNPeYHUV9KE+7Zkfk1clDfZ2WfchCPE2db+AkXpFqFR8EB69MkqpV85ac54rJHopfpZpNEIzmuac+g4rACYJ44W1lxqplE9GTY7H+nAsuAPdy+2TM=
