# pyproject.toml
[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4", "numpy", "scikit-build", "cmake>=3.15"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "fc/_version.py"

[tool.pytest.ini_options]
addopts = "--import-mode importlib"
