source_product: s2a_ard_granule
output_product: s2a_fc_granule

description: Sentinel 2A Fractional Cover
product_type: fractional_cover

location: '/g/data/fk4/datacube/002/FC/'
file_path_template: 'S2_FC/{tile_index[0]}_{tile_index[1]}/S2_FC_{tile_index[0]}_{tile_index[1]}_{start_time}_v{version}.nc'

input_mapping:
  nbart_green: green
  nbart_nir_1: nir
  nbart_red: red
  nbart_swir_2: swir1
  nbart_swir_3: swir2

sensor_regression_coefficients:
#  The coefficients is applied to band values in the 0-10,000 range, before it is scaled to a fraction
#  This means the first coefficient has been also scaled when compared to the literature
  blue:
    - -22.0
    - 0.9551
  green:
    - 31.0
    - 1.0582
  red:
    - 64.0
    - 0.9871
  nir:
    - 120.0
    - 1.0187
  swir1:
    - 79.0
    - 0.9528
  swir2:
    - -42.0
    - 0.9688

global_attributes:
  title: Fractional Cover 10 v3
  summary: 'The Fractional Cover (FC) algorithm was developed by the Joint Remote
    Sensing Research Program and is described in described in Scarth et al. (2010)
    for Landsat, and extended to Sentinel-2 as described in Flood (2017).

    FC_10 provides a 10m scale fractional cover representation of the proportions
    of green vegetation, non-green vegetation, and bare surface cover across the Australian
    continent. The fractions are retrieved by inverting multiple linear regression
    estimates and using synthetic endmembers in a constrained non-negative least squares
    unmixing model. For further information please see the articles below describing
    the method implemented which are free to read:


    Scarth, P, Roder, A and Schmidt, M 2010, ''Tracking grazing pressure and climate
    interaction - the role of Landsat fractional cover in time series analysis'',
    Proceedings of the 15th Australasian Remote Sensing & Photogrammetry Conference,


    Schmidt, M, Denham, R and Scarth, P 2010, ''Fractional ground cover monitoring
    of pastures and agricultural areas in Queensland'', Proceedings of the 15th Australasian
    Remote Sensing & Photogrammetry Conference


    Flood, Neil. 2017. ''Comparing Sentinel-2A and Landsat 7 and 8 Using Surface Reflectance
    over Australia.'', Remote Sens. 9, no. 7: 659.


    A summary of the algorithm developed by the Joint Remote Sensing Centre is also
    available from the AusCover website: http://www.auscover.org.au/purl/landsat-fractional-cover-jrsrp


    Fractional cover data can be used to identify large scale patterns and trends
    and inform evidence based decision making and policy on topics including wind
    and water erosion risk, soil carbon dynamics, land management practices and rangeland
    condition. This information is used by policy agencies, natural and agricultural
    land resource managers, and scientists to monitor land conditions over large areas
    over long time frames.'

  institution: Commonwealth of Australia (Geoscience Australia)
  instrument: OLI
  keywords: AU/GA,REFLECTANCE,EARTH SCIENCE
  keywords_vocabulary: GCMD
  platform: SENTINEL-2A
  publisher_email: earth.observation@ga.gov.au
  publisher_name: Section Leader, Operations Section, NEMO, Geoscience Australia
  publisher_url: http://www.ga.gov.au
  license: CC BY Attribution 4.0 International License
  cdm_data_type: Grid
  source: fractional cover unmixing model v2017_06_09
  uuid: cc2b37b8-e1f4-454b-a1be-09f72814c5a2
  product_suite: Fractional Cover
  acknowledgment: |
    The fractional cover algorithm was developed by the Joint Remote Sensing Research Program (JRSRP) and is
    described in Scarth et al. (2010). While originally calibrated in Queensland, a large collaborative effort
    between The Department of Agriculture & ABARES and State and Territory governments to collect additional
    calibration data has enabled the calibration to extend to the entire Australian continent.

    The conversion of the algorithm to use Sentinel-2A is described in Flood (2017).

    FC_10 was made possible by new scientific and technical capabilities, the collaborative framework established by
    the Terrestrial Ecosystem Research Network (TERN) through the National Collaborative Research Infrastructure
    Strategy (NCRIS), and collaborative effort between state and Commonwealth governments.
  references: |
    - ABARES, 2014 Australian ground cover reference sites database 2014. Australian Bureau of Agricultural and Resource Economics and Sciences, Canberra, Australia. (https://remote-sensing.nci.org.au/u39/public/html/modis/fractionalcover-sitedata-abares/index.shtml).
    - Flood, N., 2014.Continuity of Reflectance Data between Landsat-7 ETM+ and Landsat-8 OLI, for Both Top-of-Atmosphere and Surface Reflectance: A Study in the Australian Landscape. Remote Sensing, 6, 7952-7970.
    - Muir, J., Schmidt, M., Tindall, D., Trevithick, R., Scarth, P., Stewart, J., 2011. Guidelines for Field measurement of fractional ground cover: a technical handbook supporting the Australian collaborative land use and management program. Tech. rep., Queensland Department of Environment and Resource Management for the Australian Bureau of Agricultural and Resource Economics and Sciences, Canberra.
    - Scarth, P., Roder, A. and Schmidt, M., 2010. Tracking grazing pressure and climate interaction -  the role of Landsat fractional cover in the time series analysis, Proceedings of the 15th Australasian Remote Sensing & Photogrammetry Conference, viewed 4 January 2011, scribd.com/doc/37455672/15arspc-Submission-140.
    - Schmidt, M., Denham, R. and Scarth, P., 2010. 'Fractional ground cover monitoring of pastures and agricultural areas in Queensland', Proceedings of the 15th Australasian Remote Sensing & Photogrammetry Conference, viewed 4 January 2011, www.scribd.com/doc/37455826/15arspc-Submission-119.
    - Flood, N. 2017. Comparing Sentinel-2A and Landsat 7 and 8 Using Surface Reflectance over Australia. Remote Sens. 9, no. 7: 659. (https://doi.org/10.3390/rs9070659)

storage:
  driver: NetCDF CF

  crs: EPSG:3577
  tile_size:
          x: 100000.0
          y: 100000.0
  resolution:
          x: 10
          y: -10
  chunking:
      x: 200
      y: 200
      time: 5
  dimension_order: ['time', 'y', 'x']

measurements:
    - name: BS
      src_var: BS
      units: "percent"
      dtype: int8
      nodata: -1
      zlib: True
      fletcher32: True
      attrs:
          long_name: "Bare ground fraction percentage"
          comment: "Fraction of bare ground including rock, bare and disturbed soil, within the Landsat pixel as percentages"
          alias: "bare"
          coverage_content_type: modelResult
      aliases: ["bare"]
    - name: PV
      src_var: PV
      units: "percent"
      dtype: int8
      nodata: -1
      zlib: True
      fletcher32: True
      attrs:
          long_name: "Green cover fraction percentage"
          comment: "Fraction of green cover including green groundcover and green leaf material over all strata, within the Landsat pixel, as percentages"
          alias: "green"
          coverage_content_type: modelResult
      aliases: ["green_veg"]
    - name: NPV
      src_var: NPV
      units: "percent"
      dtype: int8
      nodata: -1
      zlib: True
      fletcher32: True
      attrs:
          long_name: "Non-green cover fraction percentage"
          comment: "Fraction of non green cover including litter, dead leaf and branches over all strata, within the Landsat pixel, as percentages"
          alias: "dead"
          coverage_content_type: modelResult
      aliases: ["dead_veg"]
    - name: UE
      src_var: UE
      units: "1"
      dtype: int8
      nodata: -1
      zlib: True
      fletcher32: True
      attrs:
          long_name: "Unmixing error"
          comment: "Eclidean Norm of the Residual Vector"
          alias: "err"
          coverage_content_type: qualityInformation
      aliases: ["err"]
