#!/bin/bash

#PBS -P u46
#PBS -q normal
#PBS -l walltime=00:15:00
#PBS -l mem=63GB
#PBS -l ncpus=32

set -e

QMODE=celery
PYENV=agdc
PORT=3333

ADDR=${HOSTNAME}:$PORT

# start common part
[ -z "$PBS_O_PATH" ] || export PATH="$PBS_O_PATH"
source activate $PYENV
source pbs_helpers.sh

pbs_check_or_exit
pbs_display_info
pbs_launch_workers
# end common part

# script specific part
cd ${PBS_O_WORKDIR}

# Default queue-size is way too large, leading to OOM on redis, probably needs
# tuning. Queue needs to be large enough to be never empty, but not larger, this
# is a function of how fast items can be generated by the main node, how fast
# items are processed by worker node and how many worker nodes there are.
# Currently redis memory is hard-coded to 100M without good way to change it at
# run-time, this needs to be looked at.
datacube-fc --executor $QMODE localhost:$PORT \
            --app-config ./app.yaml \
            --queue-size 100 \
            --skip-db-update \
            --process-all \
            -v -v \
            --year 1988
