name: Publish to TestPyPI

on:
  push:
    branches:
      - setup-pypi
  workflow_dispatch:

jobs:
  build_wheels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3
        env:
          CIBW_BUILD: cp310-manylinux_x86_64
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_BEFORE_ALL_LINUX: |
            yum install -y gcc-gfortran
          CIBW_TEST_SKIP: "*"

      - uses: actions/upload-artifact@v5
        with:
          name: wheels
          path: wheelhouse/*.whl

  publish:
    if: github.repository == 'GeoscienceAustralia/fc'
    needs: build_wheels
    runs-on: ubuntu-latest

    environment: testpypi

    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v6
        with:
          name: wheels
          path: dist

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true