name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.8, 3.9 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install -y \
                 libproj-dev \
                 proj-bin \
                 libgdal-dev \
                 libgeos-dev \
                 libgeos++-dev \
                 libudunits2-dev \
                 libnetcdf-dev \
                 libhdf4-alt-dev \
                 libhdf5-serial-dev \
                 gfortran
          python -m pip install --upgrade pip

          pip install GDAL=="$(gdal-config --version)"

          pip install --extra-index-url=https://packages.dea.ga.gov.au/ eodatasets digitalearthau
          pip install -r requirements.txt
          pip install pylint==1.7.4 yamllint pytest-cov pycodestyle coveralls netCDF4==1.3.1
      - name: Check code
        run: ./check-code.sh

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: dist

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: python-${{ matrix.python-version }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true

  deploy-packages:
#   deploy:
#       if: github.event_name == 'push' && github.ref == 'refs/heads/master'
#    if: startsWith(github.ref, 'refs/tags/v')
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: packages

      - name: Deploy packages
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: 'datacube-core-deployment'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2'   # optional: defaults to us-east-1
          SOURCE_DIR: 'dist'      # optional: defaults to entire repository
          DEST_DIR: 'fc'
