name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.8, 3.9 ]
    name: Airflow ${{ matrix.python-version }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: fc
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          python --version
          which python
      - name: Install conda dependencies
        run: mamba install datacube gdal # gdal is required by digitalearthau??
      - name: Install pip deps
        run: |
          pip install --extra-index-url=https://packages.dea.ga.gov.au/ eodatasets3 digitalearthau
          pip install pycodestyle pylint pylint-cov
      - name: Build package
        run: pip wheel --no-deps -w dist .
      - name: Install from directory
        run: pip install .
      - name: Check code
        run: ./check-code.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: dist

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: python-${{ matrix.python-version }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true

  deploy-packages:
#   deploy:
#       if: github.event_name == 'push' && github.ref == 'refs/heads/master'
#    if: startsWith(github.ref, 'refs/tags/v')
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: packages

      - name: Deploy packages
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: 'datacube-core-deployment'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2'   # optional: defaults to us-east-1
          SOURCE_DIR: 'dist'      # optional: defaults to entire repository
          DEST_DIR: 'fc'
